### PR TITLE
Sync GitHub Issues to Azdo

### PR DESCRIPTION
**Pull request by abahetik**
This PR adds a new workflow :
sync_github_issues_to_azdo: This workflow will create an equivalent AzDo bug for the GitHub issues
and
Fixed pushing the automated VIPB bumps to master

### CODE REVIEW

**Comment by shivaprasad-basavaraj** [comment]
This PR would duplicate only new issues right? What happens to the issues that are already raised in GitHub?

**Comment by abahetik** [comment]
> This PR would duplicate only new issues right? What happens to the issues that are already raised in GitHub?

@shivaprasad-basavaraj It will get triggered for all issue types i.e opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned

**Comment by shivaprasad-basavaraj** [comment]
> > This PR would duplicate only new issues right? What happens to the issues that are already raised in GitHub?
> 
> @shivaprasad-basavaraj It will get triggered for all issue types i.e opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned

So the issues won't be duplicated in AzDO unless they are interacted with somehow right? Is that what we are going for?

**Comment by abahetik** [comment]
> > > This PR would duplicate only new issues right? What happens to the issues that are already raised in GitHub?
> > 
> > 
> > @shivaprasad-basavaraj It will get triggered for all issue types i.e opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned
> 
> So the issues won't be duplicated in AzDO unless they are interacted with somehow right? Is that what we are going for?

@shivaprasad-basavaraj The issue won't get duplicated even when edits are made. It will just update its equivalent AzDo item. However, I think the existing issues might need to be modified to trigger the workflow

**Review by shivaprasad-basavaraj — APPROVED** [review]

**Pull request merged**
