### PR TITLE
New Service Template

### PR DESCRIPTION
**Pull request by navinsubramani**
#42  The issue is mentioned here.

Note, the development approach is similar to how the "current template" and "gRPC LabVIEW support" is linked and developed. Below is the dependency diagram.
image

Please build and install the "LabVIEW gRPC Servicer" to use the "Client Server Template New". The package that is linked here (rename the extension from .txt to .vop and install the package or build it using the build spec in the source)
[ni_lib_labview_grpc_servicer-0.3.0.5.txt](https://github.com/ni/grpc-labview/files/7573589/ni_lib_labview_grpc_servicer-0.3.0.5.txt)
,

### CODE REVIEW

**Comment by navinsubramani** [comment]
@ccifra  Committed the template components alone. Once this is reviewed and signed off, we can create an issue for the scripting tool that generates the template from one or more proto files.

**Comment by navinsubramani** [comment]
This issue is mentioned here #16 

Before this change:

When the proto file package name has a "dot" in it. For example: Package.V1.

During creation of server code, we get the server code created with issues in RPC methods
image

During creation of client code, we get an below error and client code is not created
image

This issue is fixed by doing changes in two VIs:

"Translate gRPC Method FullName" VI is changed to consider a "dot" in the package name.

From:
image

To: 
image

"Create LV RPC Method Name" VI is changed to consider a package name with dot and replace it with underscore to create a Method Name.

From: 
image

To: 
image

Test Cases:
Tested both code generation of server and client code, and basic functionality of server and client for all the below cases,
1. Proto file with no package name
2. Proto file with package name and DOT
3. Proto file with package name and no DOT

**Comment by ccifra** [comment]
Some comments on the overall structure:

End RPC Call.vi is under the RPC Messages folder.  Is there a reason for that?  It is only needed when implementing a server and I think it should be part of the server class.  I am not sure we even need it since it is just a simple wrapper around the end call VI in the LV Support library.

For the messages, do we need to add _Data to the typedef of the message or can it be just be package_templatemessage.ctl

Given the path length issues do we need to have a folder per service method?  I think it would be better to just have a single folder for all methods with a messaging and registration folder under that, but all of the method VIs would be in the same folder.

What is the purpose of "RPC Method package_service_method logic.vi"

**Comment by navinsubramani** [comment]
@ccifra 

#1 I am good with removing it, since like you mentioned it is a wrapper. All the messages contain the "set" API which closes the RPC call themselves. If we are planning to make the "end call" VI public for developers, then we can remove them.

#2 I dont see any naming spacing concerns for the message to have a _Data with it. It came from legacy template. I will remove that as well.

#3 I have them flat in file explorer, and only on the project made some virtual folders. I will probably have only a virtual folder for each method and not have many nest under it. But the files in disk are flat under RPC methods
image

#4 Given the business logic are written in the event structure, and the logic should be repliacted in Sync & Async engine and it is upto developers to create VIs to modularize them - I have created a VI for it. This VI will be dropped in the event structure of sync and Async for their respective events. So, developers need not go to sync or async engines, rather just add their service logic in this VI and both sync/async will work well.  Also, when there are changes to service in proto file, the events will break but if the logic is in this VI, we could avoid disturbing the logic.

This is the idea. Please let me know your thoughts.

**Comment by navinsubramani** [comment]
@ccifra I was recommending folks to create a VI under event structure for the logic, and this VI will help that. But maybe we need not have this for version 1, and look at it in future if this comes up. Less development now :)

Its easy to tell people to code here,
image

Rather than code here,
image

**Comment by ccifra** [comment]
That does not work as well for the streaming case or when the method changes what is being stream.  I think we should think about this aspect a little more before moving forward.

**Comment by navinsubramani** [comment]
Sure @ccifra . I was thinking about streaming and imagining will that be a blocking call or Asynchronous implementation. I guess if its in event structure case it will be a blocking call (even in VI) for other events. The logic should be implemented outside the event case for server streaming, if it should allow for other event calls meanwhile. I guess I will wait to look at the APIs and decide. For now, Will not build any placeholders for logic - It will be open.

**Comment by navinsubramani** [comment]
@ccifra Made changes mentioned above.

**Comment by ccifra** [comment]
This was resolved by PR #46 which included these changes.

**Pull request closed without merging**
