### PR TITLE
Modify dll location if running in PPL

### PR DESCRIPTION
**Pull request by pakdev**
Implements changes described in issue #75. While not the ideal solution being worked out in #144, it at least unblocks us from using this library in Record/Replay

### CODE REVIEW

**Comment by shivaprasad-basavaraj** [comment]
@pakdev Looks like the `Get Server DLL Path.vi` has been saved in LabVIEW 2020. All our VIs should be saved in LabVIEW 2019 since that's what we use to build the VIPM packages. The build_release_artifacts stage actually failed because of this but isn't being reported correctly. I have filed an issue to fix this. (#169) 

Also looks like there are issues with how the VI has been edited. It added a dependency on a `gprc-lvsupport-release.lvlib` from `Get Server DLL Path.vi` as shown in the image below. The grpc-lvsupport.lvlib gets built into the lvsupprot-release.lvlib and as such shouldn't have any dependency on the release lvlib.

image

**Review by shivaprasad-basavaraj — CHANGES_REQUESTED** [review]
Added a comment about issues with the changes to the vi.

**Comment by pakdev** [comment]
> @pakdev Looks like the `Get Server DLL Path.vi` has been saved in LabVIEW 2020. All our VIs should be saved in LabVIEW 2019 since that's what we use to build the VIPM packages. The build_release_artifacts stage actually failed because of this but isn't being reported correctly. I have filed an issue to fix this. (#169)
> 
> Also looks like there are issues with how the VI has been edited. It added a dependency on a `gprc-lvsupport-release.lvlib` from `Get Server DLL Path.vi` as shown in the image below. The grpc-lvsupport.lvlib gets built into the lvsupprot-release.lvlib and as such shouldn't have any dependency on the release lvlib.
> 
> image

Whoops, should be fixed now. Thanks!

**Review by shivaprasad-basavaraj — APPROVED** [review]
There was another issue with the `Get Server DLL Path.vi` where the reentrancy mode was set to non-reentrant. I went ahead and updated it to Preallocated clone like it was before. Also, the lvproj needed to be saved with the new dependency to check if the VI was in a PPL.

**Pull request merged**
